//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHTransaction
    {
        public int Id { get; set; }
        public System.Guid SourceParentId { get; set; }
        public int SourceId { get; set; }
        public int TransactionType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionDescription { get; set; }
        public int OriginatorType { get; set; }
        public System.Guid OriginatorId { get; set; }
        public int ReceiverType { get; set; }
        public System.Guid ReceiverId { get; set; }
        public string Name { get; set; }
    }
}
