//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHTransactionExtract
    {
        public int Id { get; set; }
        public int ACHTransactionId { get; set; }
        public int MasterExtractId { get; set; }
    
        public virtual ACHTransaction ACHTransaction { get; set; }
        public virtual MasterExtract MasterExtract { get; set; }
    }
}
