//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionExtract
    {
        public int Id { get; set; }
        public System.Guid PayrollInvoiceId { get; set; }
        public int MasterExtractId { get; set; }
    
        public virtual MasterExtract MasterExtract { get; set; }
        public virtual PayrollInvoice PayrollInvoice { get; set; }
    }
}
