//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTaxState
    {
        public int Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string EIN { get; set; }
        public string Pin { get; set; }
        public string UIAccountNumber { get; set; }
        public Nullable<int> DepositSchedule { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
