//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContract
    {
        public int Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public int Type { get; set; }
        public Nullable<int> PrePaidSubscriptionType { get; set; }
        public int BillingType { get; set; }
        public string CardDetails { get; set; }
        public string BankDetails { get; set; }
        public decimal InvoiceRate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
