//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRecurringCharge
    {
        public int Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public int OldId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> AnnualLimit { get; set; }
        public decimal Claimed { get; set; }
        public bool IsPaidInFull { get; set; }
        public string Comments { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
