//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyProject()
        {
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string AwardingBody { get; set; }
        public string RegistrationNo { get; set; }
        public string LicenseNo { get; set; }
        public string LicenseType { get; set; }
        public string PolicyNo { get; set; }
        public string Classification { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
