//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAccumlatedPayType
    {
        public int Id { get; set; }
        public int PayTypeId { get; set; }
        public System.Guid CompanyId { get; set; }
        public decimal RatePerHour { get; set; }
        public decimal AnnualLimit { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
