//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FITW4Table
    {
        public int Id { get; set; }
        public string FilingStatus { get; set; }
        public decimal DependentWageLimit { get; set; }
        public decimal DependentAllowance1 { get; set; }
        public decimal DependentAllowance2 { get; set; }
        public decimal AdditionalDeductionW4 { get; set; }
        public decimal DeductionForExemption { get; set; }
        public int Year { get; set; }
    }
}
