//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public int Id { get; set; }
        public System.Guid InvoiceId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int Method { get; set; }
        public int Status { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual PayrollInvoice PayrollInvoice { get; set; }
    }
}
