//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal InvoiceValue { get; set; }
        public decimal LineItemTotal { get; set; }
        public int Status { get; set; }
        public int RiskLevel { get; set; }
        public string LineItems { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string InvoiceNumber { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Payments { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> DeliveredOn { get; set; }
        public string DeliveredBy { get; set; }
        public int InvoiceMethod { get; set; }
        public decimal InvoiceRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
