//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinWageYear
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public Nullable<int> StateId { get; set; }
        public decimal MinWage { get; set; }
        public decimal TippedMinWage { get; set; }
        public decimal MaxTipCredit { get; set; }
    }
}
