//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayCheckExtract
    {
        public int PayrollPayCheckId { get; set; }
        public int MasterExtractId { get; set; }
        public string Extract { get; set; }
        public int Type { get; set; }
    
        public virtual MasterExtract MasterExtract { get; set; }
        public virtual PayrollPayCheck PayrollPayCheck { get; set; }
    }
}
