//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.PayrollInvoices = new HashSet<PayrollInvoice>();
            this.PayrollPayChecks = new HashSet<PayrollPayCheck>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime PayDay { get; set; }
        public int StartingCheckNumber { get; set; }
        public string Company { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public bool PEOASOCoCheck { get; set; }
        public string Notes { get; set; }
        public System.DateTime TaxPayDay { get; set; }
        public bool IsHistory { get; set; }
        public Nullable<System.Guid> CopiedFrom { get; set; }
        public Nullable<System.Guid> MovedFrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollInvoice> PayrollInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPayCheck> PayrollPayChecks { get; set; }
    }
}
