//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchTable
    {
        public int Id { get; set; }
        public int SourceTypeId { get; set; }
        public System.Guid SourceId { get; set; }
        public System.Guid HostId { get; set; }
        public System.Guid CompanyId { get; set; }
        public string SearchText { get; set; }
    }
}
