//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxYearRate
    {
        public int Id { get; set; }
        public int TaxId { get; set; }
        public int TaxYear { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> AnnualMaxPerEmployee { get; set; }
        public Nullable<decimal> TaxRateLimit { get; set; }
    
        public virtual Tax Tax { get; set; }
    }
}
