//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCustomer
    {
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Name { get; set; }
        public int StatusId { get; set; }
        public string AccountNo { get; set; }
        public bool IsVendor { get; set; }
        public bool IsVendor1099 { get; set; }
        public string Contact { get; set; }
        public string Note { get; set; }
        public Nullable<int> Type1099 { get; set; }
        public Nullable<int> SubType1099 { get; set; }
        public Nullable<int> IdentifierType { get; set; }
        public string IndividualSSN { get; set; }
        public string BusinessFIN { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Status Status { get; set; }
    }
}
