//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.OnlinePayroll.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnlinePayrollStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnlinePayrollStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HrMaxx.OnlinePayroll.Contracts.Resources.OnlinePayrollStringResources", typeof(OnlinePayrollStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EMAIL_ACH_EmployeeBody {
            get {
                return ResourceManager.GetString("EMAIL_ACH_EmployeeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH Pay Check for {0}.
        /// </summary>
        public static string EMAIL_ACH_EmployeeSubject {
            get {
                return ResourceManager.GetString("EMAIL_ACH_EmployeeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EMAIL_Company_PayrollBody {
            get {
                return ResourceManager.GetString("EMAIL_Company_PayrollBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Pack.
        /// </summary>
        public static string EMAIL_Company_PayrollSubject {
            get {
                return ResourceManager.GetString("EMAIL_Company_PayrollSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete memento..
        /// </summary>
        public static string ERROR_CouldNotDeleteMementos {
            get {
                return ResourceManager.GetString("ERROR_CouldNotDeleteMementos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve staging data..
        /// </summary>
        public static string ERROR_CouldNotRetrieveStagingData {
            get {
                return ResourceManager.GetString("ERROR_CouldNotRetrieveStagingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save memento..
        /// </summary>
        public static string ERROR_CouldNotSaveMemento {
            get {
                return ResourceManager.GetString("ERROR_CouldNotSaveMemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update staging data..
        /// </summary>
        public static string ERROR_CouldNotUpdateStagingData {
            get {
                return ResourceManager.GetString("ERROR_CouldNotUpdateStagingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move document..
        /// </summary>
        public static string ERROR_FailedToMoveDocument {
            get {
                return ResourceManager.GetString("ERROR_FailedToMoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve {0}..
        /// </summary>
        public static string ERROR_FailedToRetrieveX {
            get {
                return ResourceManager.GetString("ERROR_FailedToRetrieveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save {0}..
        /// </summary>
        public static string ERROR_FailedToSaveX {
            get {
                return ResourceManager.GetString("ERROR_FailedToSaveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCLInstanceItemId does not existing for this Photo Check List.
        /// </summary>
        public static string ERROR_InvalidPCLInstanceItemId {
            get {
                return ResourceManager.GetString("ERROR_InvalidPCLInstanceItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Resource Found..
        /// </summary>
        public static string ERROR_No_Resource_Found {
            get {
                return ResourceManager.GetString("ERROR_No_Resource_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply either a MemoryBusMessage or a ServiceBusMessage attribute for your message of type {0}.
        /// </summary>
        public static string ERROR_NoBusTargettedExceptionMessage {
            get {
                return ResourceManager.GetString("ERROR_NoBusTargettedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error {0}..
        /// </summary>
        public static string ERROR_UnexpectedError {
            get {
                return ResourceManager.GetString("ERROR_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error returned to controller..
        /// </summary>
        public static string ERROR_UnhandledErrorReturnedToController {
            get {
                return ResourceManager.GetString("ERROR_UnhandledErrorReturnedToController", resourceCulture);
            }
        }
    }
}
