// <auto-generated />
namespace HrMaxx.Common.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180411_UserRoleVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180411_UserRoleVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201804110750485_20180411_UserRoleVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
