//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.Common.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid DocumentID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentExt { get; set; }
    }
}
