//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.Common.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityType
    {
        public EntityType()
        {
            this.EntityRelations = new HashSet<EntityRelation>();
            this.EntityRelations1 = new HashSet<EntityRelation>();
        }
    
        public int EntityTypeId { get; set; }
        public string EntityTypeName { get; set; }
    
        public virtual ICollection<EntityRelation> EntityRelations { get; set; }
        public virtual ICollection<EntityRelation> EntityRelations1 { get; set; }
    }
}
