//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.Common.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingData
    {
        public System.Guid Id { get; set; }
        public string OriginatorType { get; set; }
        public System.Guid MementoId { get; set; }
        public string Memento { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
