//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMaxx.Common.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEventLog
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public int Event { get; set; }
        public string EventObject { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string EventObjectName { get; set; }
        public string EventAction { get; set; }
        public string Module { get; set; }
    }
}
